config/routes.rb
Treebook::Application.routes.draw do
  devise_for :users

  resources :statuses

  root :to => 'statuses#index'

end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :profile_name
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-fixed-top">    <!--this 3 classes navbar nb-in contain adds the navbar to the page with navbar-fixed-top added-->
      <div class="navbar-inner">
        <div class="container">
            <a href="#" class="brand ">Treebook</a>   <!--placed content inside of navbar with styling brandname-->
                <ul class="nav"> <!--adding in links to the nav bar-->
                  <li><%= link_to "All Statuses", statuses_path %></li> <!--gonna use erb with a link to function rather than an a tag with name of link All Statuses linked to a url helper method statuses_path rake routes in the shell would help you determine and find the path for the all statuses statuses_path by printing all the urls that you would use with the first coulumn showing the names of the helper methods you would use and just add _path to the file name you want to get to-->
                </ul>
        </div>
      </div>
    </div>

    <div class="container">     <!--centers the page-->       
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        
      <%= yield %>

    </div>

</body>
</html>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<!--
<h1>All Statuses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statuses.each do |status| %>
  <tr>
    <td><%= status.name %></td>
    <td><%= status.content %></td>
    <td><%= link_to 'Show', status %></td>
    <td><%= link_to 'Edit', edit_status_path(status) %></td>
    <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Status', new_status_path %> 
SCRAP ALL THE ORIGINAL TABLE HTML TO MAKE THIS PAGE LOOK BETTER
-->





<div class="page-header">
    <h1>All of the Statuses</h1>
</div>

<!--link to the new statuses and add a class to it so we can link it to a button in bootstrap and btn-success gives it a different color-->
<%= link_to "Post a New Status", new_status_path, class: "btn btn-success" %>

<!--now create a loop for all of our statuses and exits at a variable called @statuses-->
<!--each status which takes a block which would be the do which will be piped and each time it would be placed in a variable called status-->
<!--arrow and percent sign signals a erb tag-->

<% @statuses.each do |status| %>  <!--this will loop however many times there are statuses so we will create a div tag to print out the name with each status-->
<div class="status">
    <strong><%= status.name %></strong>  <!--strong tag with status variable with the methond called name-->
    <p><%= status.content %></p>  
    <div class="meta">  <!--allows us to style it later-->
      <!--<%= link_to "Show", status %> going to take out the show status link and going to add a time instead of when the status was created but when you pass status.created_at to time_ago_in_words it displays not the date but how long ago + " ago" to make it make more sense-->
      <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
       <!--for links use the links to method so you don't have to worry about the url in this case will link to Show and will pass the status object which rails will understand -->
      <!--puts the content of the status using the erb tag with the equal sign to echo the content into the page-->
      <span class="admin">
          | <%= link_to "Edit", edit_status_path(status) %>
          | <!--divider just for looks-->
          <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure you want to delete this status?"} %> <!--add the special method delete and add the data to confirm-->
      </span>
    </div>
</div>
      <!--we don't necessary want to display the edit and destroy so we will separate it in a span class of admin so we can selectively hide and show these later which edit_status_path passes the status itself so it knows which one to edit-->

<% end %> <!--closes and notes the end the loop-->

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @status.name %>
</p>

<p>
  <b>Content:</b>
  <%= @status.content %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>